version: '3.7'

services:
  nginx:
    image: nginx:alpine
    container_name: prpl_nginx
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${PROJECT_PATH}:/var/www
      - ${DOCKER_FOLDER}/nginx/config:/etc/nginx/conf.d
      - ${DOCKER_FOLDER}/nginx/include:/etc/nginx/include
      - ${DOCKER_FOLDER}/logs:/var/www/logs
      - ${DOCKER_FOLDER}/logs/nginx:/var/www/logs/nginx
    links:
      - php-8
    networks:
      - backend

  mysql:
    container_name: prpl_mysql
    restart: always
    image: mysql:latest
    command: [
        '--default-authentication-plugin=mysql_native_password'
    ]
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_USERNAME: ${MYSQL_ROOT_USERNAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_PATH}:/var/lib/mysql
    networks:
      - backend

  php-8:
    build: ./docker/
    container_name: prpl_php
    volumes:
      - ${PROJECT_PATH}:/var/www
      - ${DOCKER_FOLDER}/php.ini:/usr/local/etc/php/php.ini
      - ${DOCKER_FOLDER}/tests/_output:/var/www/tests/_output
    links:
      - mysql
    networks:
      - backend

#Selenium chrome server for acceptance testing
  chrome:
    image: selenium/standalone-chrome-debug
    container_name: prpl_selenium
    ports:
      - 4444:4444
      - 5900
    networks:
      - backend

# Networks Setup
networks:
  backend:
    name: prpl_network_backend
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_SUBNET}
