version: '3.7'

services:
  nginx:
    image: nginx:latest
    ports:
      - 8081:8080
    volumes:
      - "${DOCKER_FOLDER}/nginx/config:/etc/nginx/conf.d"
      - "${DOCKER_FOLDER}/nginx/include:/etc/nginx/include"
      - "${WEB_ROOT_PATH}/logs:/var/www/logs"
      - "${WEB_ROOT_PATH}/logs/nginx:/var/www/logs/nginx"
      - "${WEB_ROOT_PATH}:/var/www:cached"
    links:
      - php-8
    working_dir: ${WEB_WORKING_DIR}
    networks:
      - backend

  mariadb:
    restart: always
    image: mariadb:latest
    command: [
        '--character-set-server=utf8',
        '--collation-server=utf8_general_ci',
        '--default-authentication-plugin=mysql_native_password'
    ]
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_USERNAME: ${MYSQL_ROOT_USERNAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - "${MYSQL_PATH}:/var/lib/mysql"
      - "${WEB_ROOT_PATH}:/var/www"
    networks:
      - backend

  php-8:
    build: ./docker/
    volumes:
      - "${WEB_ROOT_PATH}:/var/www"
    ports:
      - "9000:9000"
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_USERNAME: ${MYSQL_ROOT_USERNAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
    links:
      - mariadb
    networks:
      - backend

# Networks Setup
networks:
  backend:
    driver: "bridge"
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_SUBNET}
