version: '3.7'

services:
  nginx:
    image: nginx:alpine
    container_name: prpl_nginx
    ports:
      - 8080:8080
    volumes:
      - ${WEB_ROOT_PATH}:/var/www
      - ${DOCKER_FOLDER}/nginx/config:/etc/nginx/conf.d
      - ${DOCKER_FOLDER}/nginx/include:/etc/nginx/include
      - ${WEB_ROOT_PATH}/logs:/var/www/logs
      - ${WEB_ROOT_PATH}/logs/nginx:/var/www/logs/nginx
    links:
      - php-8
    networks:
      - backend

  mysql:
    restart: always
    image: mysql:latest
    container_name: prpl_mysql
    command: [
        '--character-set-server=utf8',
        '--collation-server=utf8_general_ci',
        '--default-authentication-plugin=mysql_native_password'
    ]
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_USERNAME: ${MYSQL_ROOT_USERNAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_PATH}:/var/lib/mysql
      - ${WEB_ROOT_PATH}:/var/www
    networks:
      - backend

  postgres:
    image: postgres:alpine
    container_name: prpl_postgres
    ports:
      - "5432:5432"
    volumes:
      - ${POSTGRES_PATH}:/var/lib/postgresql/data
    networks:
      - backend
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secrect

  php-8:
    build: ./docker/
    container_name: prpl_php
    volumes:
      - ${WEB_ROOT_PATH}:/var/www
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    environment:
      YII_DEBUG: ${YII_DEBUG}
      YII_ENV_DEV: ${YII_ENV_DEV}
      YII_ENV: ${YII_ENV}
      MYSQL_DSN: ${MYSQL_DSN}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_USERNAME: ${MYSQL_ROOT_USERNAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      POSTGRES_PATH: ${POSTGRES_PATH}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
    links:
      - mysql
    networks:
      - backend

# Networks Setup
networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_SUBNET}
