version: '3.7'

services:
  nginx:
    container_name: prpl_nginx
    image: nginx:latest
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${PROJECT_PATH}:/var/www
      - ${DOCKER_FOLDER}/nginx/config:/etc/nginx/conf.d
      - ${DOCKER_FOLDER}/nginx/include:/etc/nginx/include
      - ${DOCKER_FOLDER}/logs:/var/www/logs
      - ${DOCKER_FOLDER}/logs/nginx:/var/www/logs/nginx
    links:
      - php-8
    networks:
      - backend

  mysql:
    container_name: prpl_mysql
    image: mysql:latest
    command: [
        '--default-authentication-plugin=mysql_native_password'
    ]
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_USERNAME: ${MYSQL_ROOT_USERNAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: always
    volumes:
      - ${MYSQL_PATH}:/var/lib/mysql
    networks:
      - backend

  postgres:
    container_name: prpl_postgres
    image: postgres:alpine
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DATABASE: ${DB_NAME}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${POSTGRES_PATH}:/var/lib/postgresql/data
    networks:
      - backend

  php-8:
    container_name: prpl_php
    build: ${DOCKER_FOLDER}
    volumes:
      - ${PROJECT_PATH}:/var/www
      - ${DOCKER_FOLDER}/logs/php:/var/logs/php
      - ${DOCKER_FOLDER}/home/.composer:/root/.composer
    links:
      - mysql
    networks:
      - backend

#Selenium chrome server for acceptance testing
  chrome:
    image: selenium/standalone-chrome-debug
    container_name: prpl_selenium
    ports:
      - 4444:4444
      - 5900
    networks:
      - backend

# Networks Setup
networks:
  backend:
    name: prpl_network_backend
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_SUBNET}
