version: '3.7'

services:
  nginx:
    container_name: prpl_nginx
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ${PROJECT_PATH}:/var/www
      - ${DOCKER_FOLDER}/nginx/config:/etc/nginx/conf.d
      - ${DOCKER_FOLDER}/nginx/include:/etc/nginx/include
      - ${DOCKER_FOLDER}/logs:/var/www/logs
      - ${DOCKER_FOLDER}/logs/nginx:/var/www/logs/nginx
    links:
      - php-8
    networks:
      - backend

  postgres:
    container_name: prpl_postgres
    image: postgres:alpine
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${POSTGRES_PATH}:/var/lib/postgresql/data
    networks:
      - backend

  php-8:
    container_name: prpl_php_8
    build: ${DOCKER_FOLDER}
    volumes:
      - ${PROJECT_PATH}:/var/www
      - ${DOCKER_FOLDER}/logs/php:/var/logs/php
      - ${DOCKER_FOLDER}/home/.composer:/root/.composer
    environment:
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
    links:
      - postgres
    networks:
      - backend

networks:
  backend:
    name: prpl_network_backend
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_SUBNET}
