kind: Deployment
apiVersion: apps/v1
metadata:
  name: prpl-deploy
  namespace: prpl
  labels:
    app: prpl-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prpl-deploy
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prpl-deploy
        deploymentconfig: prpl-deploy
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      volumes:
        - name: prpl-php8
          configMap:
            name: prpl-php8
            defaultMode: 420
        - name: prpl-supervisor
          configMap:
            name: prpl-supervisor
            defaultMode: 420
        - name: prpl-nginx
          configMap:
            name: prpl-nginx
            defaultMode: 420		
        - name: prpl
          persistentVolumeClaim:
            claimName: prpl
      containers:
        - name: prpl-deploy
          image: >-
            image-registry.openshift-image-registry.svc:5000/prpl/prpl-deploy@sha256:4260cb022fb34692b8ad9c8cee6582f462301a266776cd018338ed6b586df8c9
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          env:
            - name: YII_ENV_DEV
              value: 'false'
            - name:  YII_ENV
              value: 'prod'
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          volumeMounts:
              - name: prpl-php8
                mountPath: "/etc/php8/php-fpm.d/"
                readOnly: true
              - name: prpl-supervisor
                mountPath: "/etc/supervisor/conf.d/"
                readOnly: true
              - name: prpl-nginx
                mountPath: "/etc/nginx/conf.d/"
                readOnly: true
              - name: prpl
                mountPath: "/var/www/ppl/web/assets"
                subPath: assets
              - name: prpl
                mountPath: "/var/www/ppl/runtime"
                subPath: runtime
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
