FROM harbor.vimpelcom.ru/dockerhub/library/alpine:3.13
COPY --from=harbor.vimpelcom.ru/dockerhub/library/composer:latest /usr/bin/composer /usr/local/bin/composer
RUN apk --no-cache add \
  curl \
  git \
  net-tools \
  vim \
  nginx \
  php8 \
  php8-ctype \
  php8-curl \
  php8-dom \
  php8-fpm \
  php8-gd \
  php8-intl \
  php8-json \
  php8-mbstring \
  php8-mysqli \
  php8-pdo_mysql \
  php8-opcache \
  php8-openssl \
  php8-phar \
  php8-session \
  php8-xml \
  php8-xmlreader \
  php8-xmlwriter \
  php8-tokenizer \
  php8-zlib \
  supervisor \
  && ln -s /usr/bin/php8 /usr/bin/php

COPY docker/base/etc/supervisor/conf.d/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
#COPY etc/nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 8080
ENTRYPOINT ["/usr/bin/supervisord"]
# Let supervisord start nginx & php-fpm
CMD ["-c", "/etc/supervisor/conf.d/supervisord.conf"]

# Configure a healthcheck to validate that everything is up&running
HEALTHCHECK --timeout=10s CMD curl --silent --fail http://127.0.0.1:8080/fpm-ping



