FROM harbor.vimpelcom.ru/prpl/prpl_base:latest
ARG COMPOSER_TOKEN
COPY . /var/www/ppl/
RUN composer config -g github-oauth.github.com ${COMPOSER_TOKEN}
RUN composer install --ignore-platform-reqs --no-dev

