kind: ConfigMap
apiVersion: v1
metadata:
  name: prpl-supervisor
  namespace: prpl

data:
  supervisord.conf: |-
    [supervisord]
    nodaemon=true
    logfile=/dev/null
    logfile_maxbytes=0
    pidfile=/run/supervisord.pid

    [program:php-fpm]
    command=php-fpm8 -F
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/stderr
    stderr_logfile_maxbytes=0
    autorestart=false
    startretries=0

    [program:nginx]
    command=nginx -g 'daemon off;error_log /dev/stdout warn;' -c /etc/nginx/conf.d/nginx.conf
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/stderr
    stderr_logfile_maxbytes=0
    autorestart=false
    startretries=0

    [program:yii-queue-worker]
    process_name=%(program_name)s_%(process_num)02d
    command=/usr/bin/php /var/www/ppl/yii product-tickets-queue/listen --verbose=1 --color=0
    autostart=true
    autorestart=true
    user=root
    numprocs=1
    redirect_stderr=true
    stdout_logfile=/dev/stdout/yii-product-tickets-queue.log
