<?php
declare(strict_types = 1);

return [
	'_SERVER.HTTP_AUTHORIZATION',
	'_SERVER.PHP_AUTH_USER',
	'_SERVER.PHP_AUTH_PW',
	'_SERVER.DOL_API_MAIN_PASSWORD',
	'_SERVER.RABBIT_DOL_NSIS_PASSWORD',
	'_SERVER.JWT_KEY_PATH',
	'_SERVER.JWT_KEY_PUB_PATH',
	'_SERVER.MYSQL_ROOT_PASSWORD',
	'_SERVER.MYSQL_PASSWORD',
	'_SERVER.MINIO_ROOT_PASSWORD',
	'_SERVER.DB_PASSWORD',
	'_POST.LoginForm.password',
];